# Generated by Django 5.0.6 on 2024-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auction_description_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="bid",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
